version: 'version'
services:
  nginx:
    image: nginx:latest
    container_name: nginx_reverse_proxy
    ports:
      - "8080:80"
    depends_on:
      - fastapi
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: fastapi_location_micro_service
    ports:
      - "8085:8085"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_INTERNAL_PORT}
      - POSTGRES_HOST_NAME=${POSTGRES_INTTERNAL_HOST}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM}
      - REDIS_HOST=${REDIS_INTERNAL_HOST}
      - REDIS_PORT=${REDIS_INTERNAL_PORT}
    # depends_on: 
    #   - postgres
    #   - redis_db
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8085
    volumes:
      - ./app:/app/app

  postgres:
    image: postgres:latest
    container_name: postgres_container
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis_db:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"  # Port mapping
    volumes:
      - redis_data:/data

volumes:
  redis_data:
